# Generated by Django 2.2.24 on 2021-12-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_education_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
